import { create } from "zustand";
import { axiosInstance } from "../lib/axios";

export const useProductStore = create((set, get) => ({
  selectedProduct: [],
  selectedCategory: [],
  products: [
    // ==== TECH CATEGORY ====
    {
      id: 1,
      category: "tech",
      name: "Smart watches",
      price: "$998.00",
      order: "154 orders",
      discount: "-25%",
      desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
      imgs: [
        "/Image/tech/8.jpg",
        "/Image/tech/1.jpg",
        "/Image/tech/2.jpg",
        "/Image/tech/3.jpg",
        "/Image/tech/4.jpg",
        "/Image/tech/5.jpg",
        "/Image/tech/6.jpg",
      ],
    },
    {
      id: 2,
      category: "tech",
      name: "Laptops",
      price: "$1128.00",
      order: "120 orders",
      discount: "-15%",
      desc: "Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
      imgs: [
        "/Image/tech/7.jpg",
        "/Image/tech/1.jpg",
        "/Image/tech/2.jpg",
        "/Image/tech/3.jpg",
        "/Image/tech/4.jpg",
        "/Image/tech/5.jpg",
        "/Image/tech/6.jpg",
      ],
    },
    {
      id: 3,
      category: "tech",
      name: "GoPro cameras",
      price: "$198.00",
      order: "203 orders",
      discount: "-40%",
      desc: "Camera 4K action perfect for capturing movement.",
      imgs: [
        "/Image/tech/6.jpg",
        "/Image/tech/1.jpg",
        "/Image/tech/2.jpg",
        "/Image/tech/3.jpg",
        "/Image/tech/4.jpg",
        "/Image/tech/5.jpg",
        "/Image/tech/7.jpg",
      ],
    },
    {
      id: 4,
      category: "tech",
      name: "Headphones",
      price: "$88.00",
      order: "203 orders",
      discount: "-25%",
      desc: "High-quality wireless headphones with noise cancellation.",
      imgs: [
        "/Image/tech/5.jpg",
        "/Image/tech/1.jpg",
        "/Image/tech/2.jpg",
        "/Image/tech/3.jpg",
        "/Image/tech/4.jpg",
        "/Image/tech/6.jpg",
        "/Image/tech/7.jpg",
      ],
    },
    {
      id: 5,
      category: "tech",
      name: "Canon cameras",
      price: "$998.00",
      order: "154 orders",
      discount: "-25%",
      desc: "Professional DSLR camera for photography lovers.",
      imgs: [
        "/Image/tech/4.jpg",
        "/Image/tech/1.jpg",
        "/Image/tech/2.jpg",
        "/Image/tech/3.jpg",
        "/Image/tech/5.jpg",
        "/Image/tech/6.jpg",
        "/Image/tech/7.jpg",
      ],
    },
    {
      id: 6,
      category: "tech",
      name: "Camera EOS 2000",
      price: "$998.00",
      order: "154 orders",
      discount: "-20%",
      desc: "Canon EOS 2000 with 10x zoom black edition.",
      imgs: [
        "/Image/tech/1.jpg",
        "/Image/tech/2.jpg",
        "/Image/tech/3.jpg",
        "/Image/tech/4.jpg",
        "/Image/tech/5.jpg",
        "/Image/tech/6.jpg",
        "/Image/tech/7.jpg",
      ],
    },
    {
      id: 7,
      category: "tech",
      name: "Action Camera",
      price: "$198.00",
      order: "203 orders",
      discount: "-10%",
      desc: "Hero6 4K action camera black edition.",
      imgs: [
        "/Image/tech/3.jpg",
        "/Image/tech/1.jpg",
        "/Image/tech/2.jpg",
        "/Image/tech/4.jpg",
        "/Image/tech/5.jpg",
        "/Image/tech/6.jpg",
        "/Image/tech/7.jpg",
      ],
    },
    {
      id: 8,
      category: "tech",
      name: "GoPro HERO6",
      price: "$198.00",
      order: "203 orders",
      discount: "-18%",
      desc: "Advanced GoPro HERO6 black for extreme sports.",
      imgs: [
        "/Image/tech/2.jpg",
        "/Image/tech/1.jpg",
        "/Image/tech/3.jpg",
        "/Image/tech/4.jpg",
        "/Image/tech/5.jpg",
        "/Image/tech/6.jpg",
        "/Image/tech/7.jpg",
      ],
    },

    // ==== INTERIOR CATEGORY ====
    {
      id: 9,
      category: "interior",
      name: "Soft chairs",
      price: "$13.00",
      order: "88 orders",
      discount: "-10%",
      desc: "Comfortable soft chairs for living rooms.",
      imgs: [
        "/Image/interior/1.jpg",
        "/Image/interior/2.jpg",
        "/Image/interior/3.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/5.jpg",
        "/Image/interior/6.jpg",
        "/Image/interior/7.jpg",
      ],
    },
    {
      id: 10,
      category: "interior",
      name: "Sofa & Chair",
      price: "$30.00",
      order: "95 orders",
      discount: "-15%",
      desc: "Elegant sofa and chair combo set.",
      imgs: [
        "/Image/interior/2.jpg",
        "/Image/interior/3.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/5.jpg",
        "/Image/interior/6.jpg",
        "/Image/interior/7.jpg",
        "/Image/interior/8.jpg",
      ],
    },
    {
      id: 11,
      category: "interior",
      name: "Kitchen Dishes",
      price: "$20.00",
      order: "110 orders",
      discount: "-20%",
      desc: "Durable and stylish kitchen dish set.",
      imgs: [
        "/Image/interior/5.jpg",
        "/Image/interior/1.jpg",
        "/Image/interior/2.jpg",
        "/Image/interior/3.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/6.jpg",
        "/Image/interior/8.jpg",
      ],
    },
    {
      id: 12,
      category: "interior",
      name: "Smart Watch Stand",
      price: "$15.00",
      order: "140 orders",
      discount: "-10%",
      desc: "Interior stand for organizing smart watches.",
      imgs: [
        "/Image/interior/3.jpg",
        "/Image/interior/1.jpg",
        "/Image/interior/2.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/5.jpg",
        "/Image/interior/7.jpg",
        "/Image/interior/8.jpg",
      ],
    },
    {
      id: 13,
      category: "interior",
      name: "Kitchen Mixer",
      price: "$100.00",
      order: "200 orders",
      discount: "-30%",
      desc: "High-power kitchen mixer for chefs.",
      imgs: [
        "/Image/interior/9.jpg",
        "/Image/interior/1.jpg",
        "/Image/interior/2.jpg",
        "/Image/interior/3.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/5.jpg",
        "/Image/interior/6.jpg",
      ],
    },
    {
      id: 14,
      category: "interior",
      name: "Blenders",
      price: "$39.00",
      order: "130 orders",
      discount: "-20%",
      desc: "Powerful blenders for smoothies and juices.",
      imgs: [
        "/Image/interior/8.jpg",
        "/Image/interior/1.jpg",
        "/Image/interior/2.jpg",
        "/Image/interior/3.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/5.jpg",
        "/Image/interior/7.jpg",
      ],
    },
    {
      id: 15,
      category: "interior",
      name: "Home Appliance",
      price: "$19.00",
      order: "180 orders",
      discount: "-15%",
      desc: "Essential home appliances for daily use.",
      imgs: [
        "/Image/interior/7.jpg",
        "/Image/interior/1.jpg",
        "/Image/interior/2.jpg",
        "/Image/interior/3.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/5.jpg",
        "/Image/interior/6.jpg",
      ],
    },
    {
      id: 16,
      category: "interior",
      name: "Coffee Maker",
      price: "$19.00",
      order: "95 orders",
      discount: "-10%",
      desc: "Brew your coffee like a barista.",
      imgs: [
        "/Image/interior/8.jpg",
        "/Image/interior/1.jpg",
        "/Image/interior/2.jpg",
        "/Image/interior/3.jpg",
        "/Image/interior/4.jpg",
        "/Image/interior/5.jpg",
        "/Image/interior/6.jpg",
      ],
    },

    // ==== CLOTH CATEGORY ====
    {
      id: 17,
      category: "cloth",
      name: "T-shirt 1",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/1.jpg",
        "/Image/cloth/2.jpg",
        "/Image/cloth/3.jpg",
        "/Image/cloth/4.jpg",
        "/Image/cloth/5.jpg",
        "/Image/cloth/6.jpg",
        "/Image/cloth/7.jpg",
      ],
    },
    {
      id: 18,
      category: "cloth",
      name: "T-shirt 2",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/2.jpg",
        "/Image/cloth/1.jpg",
        "/Image/cloth/3.jpg",
        "/Image/cloth/4.jpg",
        "/Image/cloth/5.jpg",
        "/Image/cloth/6.jpg",
        "/Image/cloth/7.jpg",
      ],
    },
    {
      id: 19,
      category: "cloth",
      name: "T-shirt 3",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/3.jpg",
        "/Image/cloth/1.jpg",
        "/Image/cloth/2.jpg",
        "/Image/cloth/4.jpg",
        "/Image/cloth/5.jpg",
        "/Image/cloth/6.jpg",
        "/Image/cloth/7.jpg",
      ],
    },
    {
      id: 20,
      category: "cloth",
      name: "T-shirt 4",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/4.jpg",
        "/Image/cloth/1.jpg",
        "/Image/cloth/2.jpg",
        "/Image/cloth/3.jpg",
        "/Image/cloth/5.jpg",
        "/Image/cloth/6.jpg",
        "/Image/cloth/7.jpg",
      ],
    },
    {
      id: 21,
      category: "cloth",
      name: "T-shirt 5",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/5.jpg",
        "/Image/cloth/1.jpg",
        "/Image/cloth/2.jpg",
        "/Image/cloth/3.jpg",
        "/Image/cloth/4.jpg",
        "/Image/cloth/6.jpg",
        "/Image/cloth/7.jpg",
      ],
    },
    {
      id: 22,
      category: "cloth",
      name: "T-shirt 6",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/6.jpg",
        "/Image/cloth/1.jpg",
        "/Image/cloth/2.jpg",
        "/Image/cloth/3.jpg",
        "/Image/cloth/4.jpg",
        "/Image/cloth/5.jpg",
        "/Image/cloth/7.jpg",
      ],
    },
    {
      id: 23,
      category: "cloth",
      name: "T-shirt 7",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/7.jpg",
        "/Image/cloth/1.jpg",
        "/Image/cloth/2.jpg",
        "/Image/cloth/3.jpg",
        "/Image/cloth/4.jpg",
        "/Image/cloth/5.jpg",
        "/Image/cloth/6.jpg",
      ],
    },
    {
      id: 24,
      category: "cloth",
      name: "T-shirt 8",
      price: "$10.30",
      order: "230 orders",
      discount: "-15%",
      desc: "T-shirts with multiple colors, for men",
      imgs: [
        "/Image/cloth/1.jpg",
        "/Image/cloth/2.jpg",
        "/Image/cloth/3.jpg",
        "/Image/cloth/4.jpg",
        "/Image/cloth/5.jpg",
        "/Image/cloth/6.jpg",
        "/Image/cloth/7.jpg",
      ],
    },
  ],

  getProductById: (id) => {
    const { products } = get();
    return products.find((product) => product.id === id);
  },

  getProductsByCategory: (categoryName) => {
    const { products } = get();

    {
      categoryName !== "AllCategory"
        ? set({
            selectedCategory: products.filter(
              (product) => product.category === categoryName
            ),
          })
        : set({ selectedCategory: products });
    }
  },


  getAllPro: async()=>{
    const res= await axiosInstance.get("/product/")
    console.log(res.data.products);
    
  }
}));
